export enum QUERY_KEY {
  LOGGED_IN_USER = "LOGGED_IN_USER",
  VALIDATE_USER = "VALIDATE_USER",
  USER_SETTINGS = "USER_SETTINGS",
  VALIDATE_AUTH = "VALIDATE_AUTH",

  CREATE_CHATBOT = "CREATE_CHATBOT",
  GET_INSTRUCTIONS = "GET_INSTRUCTIONS",
  GET_CHATBOTS = "GET_CHATBOTS",
  GET_CHATBOT = "GET_CHATBOT",
  DELETE_CHATBOT = "DELETE_CHATBOT",
  

  DATASOURCES = "DATASOURCES",
  DATASOURCES_EMBEDDINGS = "DATASOURCES_EMBEDDINGS",
  DATASOURCES_PROCESS = "DATASOURCES_PROCESS",
  DATASOURCES_DELETE = "DATASOURCES_DELETE",

  ANALYTICS = "ANALYTICS",
  ANALYTICS_SUMMARY = "ANALYTICS_SUMMARY",
  ANALYTICS_CHARTS = "ANALYTICS_CHARTS",
  ANALYTICS_FEEDBACKS = "ANALYTICS_FEEDBACKS",
  TOPIC_BAR_CHART = "TOPIC_BAR_CHART",
  TOPIC_PIE_CHART = "TOPIC_PIE_CHART",
  TOPICS = "TOPICS",

  ACTIVITY_CHATLOGS = "ACTIVITY_CHATLOGS",
  ACTIVITY_MESSAGES = "ACTIVITY_MESSAGES",


  CHATBOT_ID="CHATBOT_ID",
}