export enum QUERY_KEY {
  LOGGED_IN_USER = "LOGGED_IN_USER",
  VALIDATE_USER = "VALIDATE_USER",
  USER_SETTINGS = "USER_SETTINGS",
  VALIDATE_AUTH = "VALIDATE_AUTH",

  CREATE_CHATBOT = "CREATE_CHATBOT",
  GET_CHATBOTS = "GET_CHATBOTS",
  GET_CHATBOT = "GET_CHATBOT",
  UPDATE_CHATBOT = "UPDATE_CHATBOT",
  DELETE_CHATBOT = "DELETE_CHATBOT",

  // Prompts
  PROMPTS = "PROMPTS",

  // Templates
  GET_TEMPLATES = "GET_TEMPLATES",
  GET_TEMPLATE = "GET_TEMPLATE",

  // Contacts
  GET_CONTACTS = "GET_CONTACTS",
  GET_CONTACT = "GET_CONTACT",

  // Leads
  GET_LEADS = "GET_LEADS",

  DATASOURCES = "DATASOURCES",
  DATASOURCES_EMBEDDINGS = "DATASOURCES_EMBEDDINGS",
  DATASOURCES_PROCESS = "DATASOURCES_PROCESS",
  DATASOURCES_DELETE = "DATASOURCES_DELETE",

  ANALYTICS = "ANALYTICS",
  ANALYTICS_SUMMARY = "ANALYTICS_SUMMARY",
  ANALYTICS_CHARTS = "ANALYTICS_CHARTS",
  ANALYTICS_FEEDBACKS = "ANALYTICS_FEEDBACKS",
  ANALYTICS_DASHBOARD = "ANALYTICS_DASHBOARD",
  TOPIC_BAR_CHART = "TOPIC_BAR_CHART",
  TOPIC_PIE_CHART = "TOPIC_PIE_CHART",
  TOPICS = "TOPICS",

  ACTIVITY_CHATLOGS = "ACTIVITY_CHATLOGS",
  ACTIVITY_MESSAGES = "ACTIVITY_MESSAGES",
  ACTIVITY_CONVERSATIONS = "ACTIVITY_CONVERSATIONS",
  ACTIVITY_ESCALATIONS = "ACTIVITY_ESCALATIONS",


  PERMISSIONS = "PERMISSIONS",
  ACCOUNT_MEMBERS = "ACCOUNT_MEMBERS",
  CHATBOT_ADMINS = "CHATBOT_ADMINS",
  PENDING_INVITES = "PENDING_INVITES",

  SUBSCRIPTION_PLANS = "SUBSCRIPTION_PLANS",
  CURRENT_SUBSCRIPTION = "CURRENT_SUBSCRIPTION",
  ENTITLEMENTS = "ENTITLEMENTS",

  GET_WORKSPACES = "GET_WORKSPACES",
  CREATE_WORKSPACE = "CREATE_WORKSPACE",
  WORKSPACE_INVITATIONS = "WORKSPACE_INVITATIONS",
  WORKSPACE_MEMBERS = "WORKSPACE_MEMBERS",
  WORKSPACE_BILLING = "WORKSPACE_BILLING",
  WORKSPACE_INVOICES = "WORKSPACE_INVOICES",
  WORKSPACE_CONTEXT = "WORKSPACE_CONTEXT",
  WORKSPACE_SUBSCRIPTION = "WORKSPACE_SUBSCRIPTION",
  WORKSPACE_ENTITLEMENTS = "WORKSPACE_ENTITLEMENTS",
  INVITATION = "INVITATION",
}