export const ACTIVITY_LIST_INITIAL_PAGE_SIZE = 50;
export const ACTIVITY_LIST_PAGE_SIZE = 50;
export const ACTIVITY_LIST_BACKEND_MAX_PAGE_SIZE = 200;
export const ACTIVITY_LIST_SEARCH_DEBOUNCE_MS = 500;
